---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    template:
      engineVersion: v2
      data:
        FRIGATE_MQTT_USERNAME: "{{ .frigate_username }}"
        FRIGATE_MQTT_PASSWORD: "{{ .frigate_password }}"
  dataFrom:
    - extract:
        key: mosquitto
