---
logger:
  default: info

mqtt:
  host: mosquitto.home-automation.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

model:
  path: plus://28928a5c0eb9667ea825e0a92be656e7

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: pci

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  hwaccel_args: ["-hwaccel", "vaapi", "-hwaccel_device", "/dev/dri/renderD128", "-hwaccel_output_format", "yuv420p"]
  output_args:
    record: preset-record-ubiquiti

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 30

record:
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects

objects:
  track:
    - dog
    - person
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

audio:
  enabled: true
  listen:
    - ambulance
    - bark
    - bicycle
    - boom
    - eruption
    - fire_alarm
    - fire_truck
    - firecracker
    - fireworks
    - glass
    - gunshot
    - police_car
    - scream
    - shatter
    - yell
go2rtc:
  streams:
    driveway: rtsp://10.19.1.2:7441/WjHw7xRNPgqzniwQ
    garage: rtsp://10.19.1.2:7441/GzFDm5cobcQIRFw5
    doorbell: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.19.3.213:554/h264Preview_01_main
    penny: rtsp://10.19.1.2:7441/GxLlVg1VDH6Xg3UR
    package: rtsp://10.19.1.2:7441/3ukyRqs4xFzEsQCX
    living_room: rtsp://10.19.1.2:7441/bsJxnITzpvQrX0LY

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://10.19.1.2:7441/IqFZ153hVOH6xWuz
          roles: ["detect", "audio"]
        - path: rtsp://localhost:8554/driveway
          roles: ["record"]
    detect:
      width: 640
      height: 360
      fps: 10
    objects:
      track:
        - car
        - cat
        - dog
        - package
        - person
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://10.19.1.2:7441/KJwxanJXFkLWnP0Z
          roles: ["detect", "audio"]
        - path: rtsp://localhost:8554/garage
          roles: ["record"]
    detect:
      width: 640
      height: 360
      fps: 10

  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.19.3.213:554/h264Preview_01_sub
          roles: ["detect", "audio"]
        - path: rtsp://localhost:8554/doorbell
          roles: ["record"]
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - cat
        - dog
        - package
        - person
      filters:
        person:
          mask:
            - 193,199,421,205,640,201,640,0,264,0,0,0,0,189,0,166
  penny:
    ffmpeg:
      inputs:
        - path: rtsp://10.19.1.2:7441/sU72sRrCCgUcpD6u
          roles: ["detect", "audio"]
        - path: rtsp://localhost:8554/penny
          roles: ["record"]
    detect:
      width: 640
      height: 360
      fps: 10
    objects:
      track:
        - dog

  package:
    ffmpeg:
      inputs:
        - path: rtsp://10.19.1.2:7441/Soojo08SvgiioUEc
          roles: ["detect", "audio"]
        - path: rtsp://localhost:8554/package
          roles: ["record"]
    detect:
      width: 640
      height: 360
      fps: 10
    objects:
      track:
        - package

  living_room:
    detect:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://10.19.1.2:7441/m2ObtOh0cHVkWo3
          roles: ["detect", "audio"]
        - path: rtsp://localhost:8554/living_room
          roles: ["record"]
