---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ollama-backend
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: "./kubernetes/apps/selfhosted/ollama/backend"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ollama-ui
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: "./kubernetes/apps/selfhosted/ollama/ui"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
