ansible_become_pass: ENC[AES256_GCM,data:J7xg4GHMGAm++A==,iv:jyKRW8ZazfzInNyPssFsjYaigIlr9pOifnVRRxeLAzU=,tag:mgqJI55FqTY08AFyGzKPsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qe4ygqmzuawv5pzvdyv8kcwyk7x8s66m6rd3ftxugwpzexn40ueqgeuac5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RGRUbE9yWE1xWTZQT2RI
            NzF6S2Jha1J1Q3VSUlgyUFBZTGJnNU9WRWhFCmJJRlZzOEF4OGVRdjZ3ZTNCa3Ix
            dXhjZXUyMTNWRlJoSUxnVTBRbURjc2cKLS0tIExsSWNxUldCRDN6ZlpieE45NVhk
            Y3k4QVhXUklyMzJFOUNTaHZjTjUrSFEKjHBuQDLKY3olSq3vgDh+XGbIJnp2pVdf
            YhM67cYCHjjuY5pbxUldDJFRYhstpBwemW1rI0XzsA50h7KiOFQgkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T01:26:25Z"
    mac: ENC[AES256_GCM,data:cTA+NwNkKP+hvVGcb270p2o+xjD8SRIM4RMwlcu2c1ckqKXSwLjGMCdSEcH1RpAIkIa5WvYvD8jWpYkQukKrQbCpnHlZo1iTnGJhF8RL/IC0bXkKoaNbt8wfnicwi6rQLZWxkWKzT4KA9nQEjjoYJaUiRfY9+V0fmWK2fkitqgY=,iv:y06NHNl1zFcw0y3MEbdjv6QrL/5apIrpSY4Fzh3sBFE=,tag:AoLvF8k0tDTTYO2ZG5aX7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
