ansible_become_pass: ENC[AES256_GCM,data:3DXIjwQd5gzLEA==,iv:M3My8EQSFxrLVKs2J5YUlETvwYIekPRxN/OioGQ3JwM=,tag:fnow3RDTDYRPmUHiujUCkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qe4ygqmzuawv5pzvdyv8kcwyk7x8s66m6rd3ftxugwpzexn40ueqgeuac5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqT3p4NnpGN3hsdWQ3dVRO
            d21DV3Rwb1k5ZlRHd1ZQVERSemtuSlhHQjBnCjBEeS9vQkFBVVU4T09nTGNyOEdL
            cmtYZ3hOeVh1WDlYTmJNaVJ6d2ZkTUUKLS0tIFEwWUl1Y1d2Yy9Fb2Y3dlJUUDJ3
            ajNWNmRRZW9PNlI3b3EvN3o1di9Fb0EKWzq9gT48ujz7dqvs5NJiDGDjdDKyAvUt
            FiL4oOz6dw0uU8EGyRCqOxdbaREenWgTK9v1B7lpH9g3y6J0U+BmVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T01:45:13Z"
    mac: ENC[AES256_GCM,data:2iz+7hp0DxSckzwRin5j05ll8dYqexYyNc26vCc7VC3ijb0XHLw9ELbjgW2PLc04xDF2GPakPPmoB1R+FjWjEPC0m54JyzXXqmWANjsDr3iffTSHkoFgxjDl2uni3Fz3DOO9egrxb3oQgbVcqMbdHJIlKZAU/j7Hub6fhSHxF9Q=,iv:BrJdq3o7ZuheeNgHepzKnUUXl/qeqqShv4Y4FfSTAqU=,tag:J3fsZC0xkl2JXU0ZB8YMLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
