ansible_become_pass: ENC[AES256_GCM,data:gUFm5dWbaUBPXQ==,iv:pYW8hIK3KszI/VxQZ0HH2u4Bi4oVnns+FjgYdPjtNKg=,tag:rbCOAVB+n+PMyO/pE6TRsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qe4ygqmzuawv5pzvdyv8kcwyk7x8s66m6rd3ftxugwpzexn40ueqgeuac5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMkErVDZpZTFyQW5xOTBH
            aThQeVdKZkUzR2ZINDd5UHRFTVlHVEdDTWpJCmtieUJ3T05XS09CLzUwR0xCaWxy
            L0UyS2wzVWYxYmhuUGlXZy83UFFYWHMKLS0tIE5qc2xBWmY3MmV0RHExWjRLaE8v
            b0NUNXBDZkVPM2FaSURVRlJOenZqQ2MKhNTjsGvRr9dYrc/wE+CswceUbFLJa1TT
            bKS9/HrRdX9n8YdABBI/VcahNH4IYfYhBsLnl9fOgHkZ3Lq51AS1TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T01:45:13Z"
    mac: ENC[AES256_GCM,data:iqDgsWsT0IybJUH8A22B8pd9E3SP+LRVM1e9wzoOfXX3gTBXl1xYE/S+gysqemZziLPG0pfhnjpADF55hRAKRCAxIhFmBBV/LinKUohifSeHPHvCSrndltlOdL1amDEBem+vYFfm4/tK9KLpcEUZQ9pYyl7zo7N8oJQdb/hsAg8=,iv:YJ7DozXXhTEkfxGXmQPktjotT/xqykgAoX45bZOVYM8=,tag:HCGJLmYK6kAbKKQHRH8t2A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
