---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vpn-gateway
  namespace: vpn-gateway
spec:
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  interval: 15m
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.10.0@sha256:d728eac85f750b37c96a0dafd038561ea4b8035857802be1128ea9b19c61e181
    addons:
      vpn:
        enabled: true
        type: gluetun
        image:
          repository: docker.io/qmcgaw/gluetun
          tag: v3.36.0@sha256:011bea4f0743864d4eda5a569217a6fe18e3a52f5d6df31b4ceb9f7763bfbf6b
        env:
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: 'off'
          - name: DOT
            value: 'off'
          - name: HEALTH_VPN_DURATION_INITIAL
            value: 30s
          - name: UPDATER_PERIOD
            value: 1h
          - name: WIREGUARD_ALLOWED_IPS
            value: 0.0.0.0/0
          - name: VPN_SERVICE_PROVIDER
            valueFrom:
              secretKeyRef:
                name: vpn-gateway
                key: VPN_SERVICE_PROVIDER
          - name: SERVER_COUNTRIES
            valueFrom:
              secretKeyRef:
                name: vpn-gateway
                key: SERVER_COUNTRIES
          - name: WIREGUARD_ADDRESSES
            valueFrom:
              secretKeyRef:
                name: vpn-gateway
                key: WIREGUARD_ADDRESSES
          - name: WIREGUARD_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: vpn-gateway
                key: WIREGUARD_PRIVATE_KEY
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        netshoot:
          enabled: true

        networkPolicy:
          # Dsiable for now to fix DHCP
          enabled: false
          egress:
            - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
              ports:
                - port: &vpnPort 51820
                  protocol: UDP

      podAnnotations:
        configmap.reloader.stakater.com/reload: *app
        secret.reloader.stakater.com/reload: *app

    routed_namespaces:
      - download

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_TRAFFIC_PORT: *vpnPort
      VXLAN_ID: 999

    webhook:
      gatewayDefault: false
      gatewayAnnotation: setGateway
      gatewayLabel: setGateway
      namespaceSelector:
        type: label
        label: vpn-routed-gateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0@sha256:a8ed630613de277244dfe203cd11d05905d7eeba8d8c41e399b02ee9a847b2f5
