---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app mosquitto
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.20
            command:
              - "/bin/sh"
              - "-c"
            args:
              - cp /tmp/secret/* /mosquitto/external_config/;
                mosquitto_passwd -U /mosquitto/external_config/mosquitto_pwd;
                chmod 0600 /mosquitto/external_config/mosquitto_pwd;

        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.20
            resources:
              requests:
                cpu: 5m
                memory: 10M
              limits:
                memory: 10M

    service:
      main:
        controller: mosquitto
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "mqtt.${SECRET_DOMAIN}"
        externalTrafficPolicy: Cluster
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          main:
            main:
              - path: /data
      mosquitto-configfile:
        type: configMap
        name: mosquitto-configmap
        advancedMounts:
          main:
            main:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
      mosquitto-secret:
        type: secret
        name: mosquitto
        advancedMounts:
          main:
            init-config:
              - path: /tmp/secret
      mosquitto-externalconfig:
        type: emptyDir
        globalMounts:
          - path: /mosquitto/external_config
