---
kubernetes:
  children:
    master:
      hosts:
        k8s-1:
          ansible_user: ctso
          ansible_host: 10.19.1.41
        k8s-2:
          ansible_user: ctso
          ansible_host: 10.19.1.42
        k8s-3:
          ansible_user: ctso
          ansible_host: 10.19.1.43
