---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hajimari
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 15m
  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
    hajimari:
      title: ${SECRET_DOMAIN}
      lightTheme: gazette
      darkTheme: tron
      namespaceSelector:
        matchNames:
          - home-automation
          - selfhosted
      showGreeting: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: http://authelia.security.svc.cluster.local/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Method $request_method;
          hajimari.io/enable: "false"
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${SECRET_DOMAIN}"
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 10m
        memory: 64M
      limits:
        memory: 64M
