---
authentication_backend:
  file:
    path: /config/users.yaml

access_control:
  default_policy: one_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8"]
  rules:
    - domain: "ubuntu-vnc.${SECRET_DOMAIN}"
      policy: one_factor
      subject:
        - ['group:admin']

session:
  cookies:
    - name: authelia_session
      domain: "${SECRET_DOMAIN}"
      authelia_url: https://auth.${SECRET_DOMAIN}
      default_redirection_url: https://${SECRET_DOMAIN}

storage:
  local:
    path: /data/db.sqlite3

notifier:
  disable_startup_check: true
  filesystem:
    filename: /data/notification.txt

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "$${GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: one_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.${SECRET_DOMAIN}/login/generic_oauth"]
        userinfo_signed_response_alg: none
