---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./atuin/ks.yaml
  - ./hajimari/ks.yaml
  - ./mealie/ks.yaml
  - ./paperless/ks.yaml
  - ./ollama/ks.yaml
  - ./actual/ks.yaml
