---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zwave-js-ui
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    controllers:
      zwavejs:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/zwave-js/zwave-js-ui
              tag: 9.25.0@sha256:f00866bdc2376e19bad2b8db94d056107279efd5277447c9229d16315f33cd82
            env:
              TZ: America/Los_Angeles
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8091
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              privileged: true
            resources:
              limits: &resources
                memory: 512Mi
              requests:
                <<: *resources
                cpu: 10m
        pod:
          nodeSelector:
            aeotec.feature.node.kubernetes.io/zwave: "true"
    service:
      main:
        controller: zwavejs
        ports:
          http:
            port: *port
          websocket:
            port: 3000
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "zwave.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: zwave-js-ui
        globalMounts:
          - path: /usr/src/app/store
      usb:
        type: hostPath
        hostPath: /dev/serial/by-id/usb-0658_0200-if00
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/serial/by-id/usb-0658_0200-if00
