---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ftp
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    controllers:
      main:
        strategy: Recreate

        containers:
          main:
            image:
              repository: fauria/vsftpd
              tag: latest@sha256:6d71d7c7f1b0ab2844ec7dc7999a30aef6d758b6d8179cf5967513f87c79c177

            env:
              FTP_USER: paperless
              FTP_PASS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_FTP_PASSWORD
              PASV_ADDRESS: &ipaddr 10.19.96.100
              PASV_MIN_PORT: 21100
              PASV_MAX_PORT: 21103
              LOG_STDOUT: "true"
              REVERSE_LOOKUP_ENABLE: "false"


    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: *ipaddr
        ports:
          http:
            port: 21
          pasv0:
            port: 21100
            enabled: true
          pasv1:
            port: 21101
            enabled: true
          pasv2:
            port: 21102
            enabled: true
          pasv3:
            port: 21103
            enabled: true

    ingress:
      main:
        enabled: false

    persistence:
      consume:
        enabled: true
        existingClaim: paperless-nfs
        globalMounts:
          - path: /home/vsftpd/paperless
            subPath: incoming
