---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: blocky
    files:
      - config/config.yml
generatorOptions:
  disableNameSuffixHash: true
