---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app grafana
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: "./kubernetes/apps/monitoring/grafana/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  dependsOn:
    - name: kube-prometheus-stack
    - name: external-secrets-stores
