---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 10Gi
