---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-lan
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-lan",
      "plugins": [
        {
          "type": "vlan",
          "master": "eth0",
          "vlanId": 2,
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "10.19.2.0/24", "gw": "10.19.2.1" }
            ]
          }
        }
      ]
    }
