---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.58.2@sha256:6dc3334d142df48cdf9876152762aff4f17df46c62507f2b4fb07179882a1962
            env:
              NO_AUTOUPDATE: true
              PORT: &port "41642"
              TS_HOSTNAME: "k8s-gateway"
              TS_EXTRA_ARGS: --advertise-exit-node --advertise-tags=tag:k8s
              TS_KUBE_SECRET: "tailscale-state"
              TS_ROUTES: 10.19.96.0/24,10.19.1.40/32
              TS_TAILSCALED_EXTRA_ARGS: --debug=0.0.0.0:2000
              TS_USERSPACE: true
              TZ: America/Los_Angeles
            envFrom:
              - secretRef:
                  name: tailscale
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1024Mi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      tmp:
        type: emptyDir
    service:
      main:
        ports:
          http:
            port: 2000
    serviceAccount:
      name: tailscale
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /debug/metrics
            interval: 1m
            scrapeTimeout: 30s
