---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.56.1@sha256:ac0c192f6cba52877e4d9c2fe8943f16c0ab44927605a21416852590e3ccb71e
            env:
              NO_AUTOUPDATE: true
              PORT: &port "41642"
              TS_EXTRA_ARGS: --advertise-exit-node --advertise-tags=tag:k8s
              TS_KUBE_SECRET: "tailscale-state"
              TS_ROUTES: 10.19.96.0/24
              TS_TAILSCALED_EXTRA_ARGS: --debug=0.0.0.0:2000
              TS_USERSPACE: true
              TZ: America/Los_Angeles
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      tmp:
        type: emptyDir
    service:
      main:
        ports:
          http:
            port: 2000
      tailnet:
        controller: main
        type: LoadBalancer
        ports:
          tailnet-udp:
            enabled: true
            port: *port
            protocol: UDP
    serviceAccount:
      name: tailscale
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /debug/metrics
            interval: 1m
            scrapeTimeout: 30s
